### PR TITLE
Swap evolution call to `Grid::evolve`

### PR DESCRIPTION
**Pull request by felixhekhorn**
once a new pineappl version becomes available, it has to be added to `pyproject.toml`

### CODE REVIEW

**Comment by cschwan** [comment]
Here you go: https://github.com/NNPDF/pineappl/releases/tag/v0.5.8.

**Comment by AleCandido** [comment]
@andreab1997 if you can (or whenever you can) test that:

- you can produce known FkTables with `grid.evolve`
- they have same predictions of the known ones
- do also for a few scale varied ones

**Comment by cschwan** [comment]
Testing with scale-varied operators is especially important!

**Comment by scarlehoff** [comment]
FWIW, the following two fktables have been computed using the `pineko` version from `pip` and the version from this branch:

401 is the new one.

```
pineappl diff 400/ATLASZPT8TEVYDIST-ATLASZPT8TEVYDIST-BIN2_ptZ.pineappl.lz4 401/ATLASZPT8TEVYDIST-ATLASZPT8TEVYDIST-BIN2_ptZ.pineappl.lz4 NNPDF40_nnlo_as_01180 --ignore-lumis
LHAPDF 6.3.0 loading /usr/local/share/LHAPDF/NNPDF40_nnlo_as_01180/NNPDF40_nnlo_as_01180_0000.dat
NNPDF40_nnlo_as_01180 PDF set, member #0, version 1; LHAPDF ID = 331100
b    x1                O(as^0 a^0)             
--+---+---+------------+------------+----------
 0   0   2  4.6120146e2  4.6120146e2 -3.331e-16
 1   2   4  2.2828456e3  2.2828456e3 -9.992e-16
 2   4   6  2.0523921e3  2.0523921e3    0.000e0
 3   6   8  5.1261271e3  5.1261271e3  6.661e-16
 4   8  10  5.6165255e3  5.6165255e3  8.882e-16
 5  10  13  4.3054435e3  4.3054435e3  6.661e-16
 6  13  16  3.0897082e3  3.0897082e3 -9.992e-16
 7  16  20  2.2202565e3  2.2202565e3    0.000e0
 8  20  25  1.5329859e3  1.5329859e3 -9.992e-16
 9  25  30  1.0757485e3  1.0757485e3 -2.220e-16
10  30  37  7.4111142e2  7.4111142e2 -3.331e-16
11  37  45  4.9319011e2  4.9319011e2  6.661e-16
12  45  55  3.2272279e2  3.2272279e2    0.000e0
13  55  65  2.0720390e2  2.0720390e2  6.661e-16
14  65  75  1.3704679e2  1.3704679e2 -2.220e-16
15  75  85  9.0124775e1  9.0124775e1 -3.331e-16
16  85 105  5.2197556e1  5.2197556e1    0.000e0
17 105 150  1.9733901e1  1.9733901e1    0.000e0
18 150 200  5.6925619e0  5.6925619e0  6.661e-16
19 200 900 2.3580250e-1 2.3580250e-1  6.661e-16
Thanks for using LHAPDF 6.3.0. Please make sure to cite the paper:
  Eur.Phys.J. C75 (2015) 3, 132  (http://arxiv.org/abs/1412.7420)
```

The luminosities between the two fktables differ however. Not sure whether I should worry about that?

**Comment by cschwan** [comment]
These differences mean that you have perfect agreement up to numerical noise: relative differences of `1e-16` means that you have roughly 16 correct digits!

**Comment by andreab1997** [comment]
Since just one line is changed in this PR I would close this without merging and open a new one (it is really one line so it is not worth spending time solving the conflicts). Do you agree?

**Review by AleCandido — APPROVED** [review]

**Pull request merged**
